spring:
  application:
    name: Auth Service
  data:
    mongodb:
      uri: ${MONGODB_URI}
  kafka:
    enabled: false
    bootstrap-servers: localhost:9092

base-url: ${BASE_URL:http://localhost:8080}

sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from: ${SENDGRID_FROM:noreply@teachme.com}

springdoc:
  api-docs:
    path: /swagger/auth-service/api-docs
