spring:
  application:
    name: Auth Service
  data:
    mongodb:
      uri: ${MONGODB_URI}

sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from: ${SENDGRID_FROM:noreply@teachme.com}
  base-url: ${BASE_URL:http://localhost:8080}

# Kafka server configuration
kafka-config:
  bootstrap-server: http://kafka:9092
  # The service name, e.g student-service for convention
  group-id: auth-service
