# Used for manual testing of the REST API.
# You can run the requests in this file by 
# using the REST Client extension for vscode

@baseurl = http://localhost:8081/api/v1
@content-type = application/json

@userId = {{me.response.body.id}}
@email = Prueba@gmail.com
@password = 123456
@token = {{signin.response.body.token}}

###

# @name me
GET {{baseurl}}/auth/me HTTP/1.1
Authorization: Bearer {{token}}

###

# @name signin

POST {{baseurl}}/auth/signin HTTP/1.1
Content-Type: {{content-type}}

{
    "email": {{email}},
    "password": {{password}}
}


###

# @name register
POST {{baseurl}}/auth/register HTTP/1.1
Content-Type: {{content-type}}

{
    "username": {{email}},
    "password": {{password}}
}

###

# @name validate
GET {{baseurl}}/auth/validate HTTP/1.1
Content-Type: {{content-type}}
Authentication: Bearer {{token}}


###

# @name listAllUsers
GET {{baseurl}}/user HTTP/1.1
Authorization: Bearer {{token}}

###

# @name createUser

POST {{baseurl}}/user HTTP/1.1
Content-Type: {{content-type}}

{
    "email": {{email}},
    "password": {{password}}
}

###

# @name getUser

GET {{baseurl}}/user/{{userId}} HTTP/1.1
Authorization: Bearer {{token}}

###

# @name deleteUser

DELETE {{baseurl}}/user/{{userId}} HTTP/1.1
Authorization: Bearer {{token}}
